/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dialog/': RouteRecordInfo<'/dialog/', '/dialog', Record<never, never>, Record<never, never>>,
    '/form/': RouteRecordInfo<'/form/', '/form', Record<never, never>, Record<never, never>>,
    '/form/child': RouteRecordInfo<'/form/child', '/form/child', Record<never, never>, Record<never, never>>,
    '/knowledge-graph/': RouteRecordInfo<'/knowledge-graph/', '/knowledge-graph', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/system/authority/': RouteRecordInfo<'/system/authority/', '/system/authority', Record<never, never>, Record<never, never>>,
    '/system/authority/edit': RouteRecordInfo<'/system/authority/edit', '/system/authority/edit', Record<never, never>, Record<never, never>>,
    '/system/role/': RouteRecordInfo<'/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/role/edit': RouteRecordInfo<'/system/role/edit', '/system/role/edit', Record<never, never>, Record<never, never>>,
    '/system/user/': RouteRecordInfo<'/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
    '/system/user/edit': RouteRecordInfo<'/system/user/edit', '/system/user/edit', Record<never, never>, Record<never, never>>,
    '/table/': RouteRecordInfo<'/table/', '/table', Record<never, never>, Record<never, never>>,
  }
}
